### ISSUE TITLE
Clearer Readme

### ISSUE THREAD

**Issue by dhiraj-das** [FirebaseGoodies/FireAdmin#13]
I am complete noob with angular and could not run the project on my local machine.
Can you complete the multi project installation steps instead of the comments.

**Comment by AXeL-dev** [comment]
Hey,

You can just ignore the comment about the frontend app since the project should work without it, just follow all the steps in order & ignore what i said in the comments.

> Can you complete the multi project installation steps instead of the comments.

I'll try to look at it this weekend, but i already tested all the steps more than once, so please check if your issue is not coming from something else (maybe a slow connection, bad files permissions or something like that).

Can you also provide more details about:
- the issue (error code/message)
- your OS
- which Angular cli version you're using

Thanks.

**Comment by dhiraj-das** [comment]
Apologies. I was able to run the demo app by reading / google'ing a bit more clearly the steps that you had mentioned.
Really appreciate your quick response.

What would be more beneficial is if you could tell me what are the areas, I need to change in case I have a custom schema rather than a page / posts type of firestore collections

**Comment by dhiraj-das** [comment]
To give you more context, I had a flutter app with daily news and quizzes which gets uploaded. I want to customize this project to adopt the schema in my firebase project but utilize the beautiful UI that you have made as an admin dashboard.

**Comment by AXeL-dev** [comment]
> Apologies. I was able to run the demo app by reading / google'ing a bit more clearly the steps that you had mentioned.

Cool x)

> To give you more context, I had a flutter app with daily news and quizzes which gets uploaded. I want to customize this project to adopt the schema in my firebase project but utilize the beautiful UI that you have made as an admin dashboard.

I don't know if you have forked the project or just followed the steps on the README, but in your case, you have to clone the project & modify it, i'll give you a quick example: for the `news` collection you can use the `posts` collection on FireAdmin & modify it. The modification(s) have to be done on:
1. [post model](https://github.com/FirebaseGoodies/FireAdmin/blob/master/projects/fire-admin/src/lib/models/collections/post.model.ts)
2. [posts service](https://github.com/FirebaseGoodies/FireAdmin/blob/master/projects/fire-admin/src/lib/services/collections/posts.service.ts)
3. & finally the [post components](https://github.com/FirebaseGoodies/FireAdmin/tree/master/projects/fire-admin/src/lib/components/posts)

You can even create a `news` model, service & components based on the `posts` ones then add or hide the sidebar entries you don't need on the [sidebar component](https://github.com/FirebaseGoodies/FireAdmin/blob/e46b7f0daac704dbf9f52aca77fc6b68ee3eedf3/projects/fire-admin/src/lib/components/shared/sidebar/sidebar.component.html#L54).

P.S.: since you're not familar with Angular, i suggest you to get a [crash course](https://www.google.com/search?q=Angular+crash+course) (just to get a minimum understanding of the code you're going to touch).

**Comment by AXeL-dev** [comment]
Also, if you liked the UI, have a look at the [shards-dashboard](https://github.com/DesignRevision/shards-dashboard) repository.

**Comment by dhiraj-das** [comment]
sweet!

Thank you so much! You are a life saver!

**Comment by dhiraj-das** [comment]
@AXeL-dev I have a field that is of type timestamp in my firestore document. How do I take care of that? Any suggestions.

The posts model has number and string. How best to store the timestamp though

**Comment by AXeL-dev** [comment]
> @AXeL-dev I have a field that is of type timestamp in my firestore document. How do I take care of that? Any suggestions.
> 
> The posts model has number and string. How best to store the timestamp though

In my opinion, the cleaner way of doing this is the following:

- Use the `firestore.Timestamp` type on the timestamp fields like so:
```ts
import { firestore } from 'firebase/app';

export interface Post {
date: firestore.Timestamp,
...
}
```

- then :point_down::

### Store case

```diff
 this.posts.add({
-   date: new Date(this.date).getTime(),
+   date: new Date(this.date),
...
 })
```

### Display case

- Add a timestamp pipe in the [pipes folder](https://github.com/FirebaseGoodies/FireAdmin/tree/master/projects/fire-admin/src/lib/pipes) with the following content (use `timestamp.pipe.ts` as a name if you like to):
```ts
import { Pipe } from '@angular/core';
import { DateTimePipe } from './datetime.pipe';
import { firestore } from 'firebase/app';

@Pipe({
  name: 'timestamp'
})
export class TimestampPipe extends DateTimePipe {

  transform(value: any, format?: string, timezone?: string, locale?: string): string {
    if (value instanceof firestore.Timestamp) {
      value = new Date(+value.seconds * 1000);
    }
    return super.transform(value, format, timezone, locale);
  }

}
```
:warning: don't forget to declare the pipe in [the main module](https://github.com/FirebaseGoodies/FireAdmin/blob/e46b7f0daac704dbf9f52aca77fc6b68ee3eedf3/projects/fire-admin/src/lib/fire-admin.module.ts#L102).

- Finally, use the the pipe on your components, example:
```html
<td>{{ post.date | timestamp }}</td>
```

**Comment by dhiraj-das** [comment]
Thank you so much @AXeL-dev ! This is one of the most detailed answers I have received for a question asked on an open-source project!

The comments are really helpful and I should be able to modify it as per my needs. <3
